### ISSUE TITLE
Test 

### ISSUE THREAD

**Issue by slushkovsky** [GeoIrb/First#3]
### Проверка результатов

Тесты выполняются, однако проверка правильности результатов не производится

### NULL pointer 

Не производится проверка на assert при вызове c NULL указателем

**Comment by GeoIrb** [comment]
Я проверяю правильность ответов с помощью функции IsEql


18 июля 2016 г., 16:13 пользователь Лушковский Сергей <
notifications@github.com> написал:

**Comment by slushkovsky** [comment]
Ок, т.е. в первой части assert'ов ты просто смотришь кол-во корней?

**Comment by GeoIrb** [comment]
Да, а там где есть корни, я их проверяю

2016-07-18 16:23 GMT+04:00 Лушковский Сергей <notifications@github.com>:

**Comment by slushkovsky** [comment]
@GeoIrb Ок, понял
